### ISSUE TITLE
Performances of SSC and Asynet are not identical?

### ISSUE THREAD

**Issue by eugenelyj** [uzh-rpg/rpg_asynet#11]
Thansk for your work and sharing.

I notice that performaces of SSC and Asynet(labeled Ours) reported at paper (Table.3, Table.4) are not the same? What is the reason? Since Asynet should output identical result.

**Comment by MessikommerNico** [comment]
You are correct. The asynchronous sparse updates are equivalent to the synchronous sparse updates.  In Table 3, we referred with "SSC [25]" to the dense VGG13 network used in [25]. The accuracy values of "SSC [25]" reported in Table 3 are the same as the values in Table 1 under "Standard Conv. -  Event Histogram". Looking back, it was maybe not a smart idea to refer in Table 3 to "SSC [25]".
In Table 4, we compare SSC/Asynet and standard convolutions for different event representations.

**Comment by eugenelyj** [comment]
Got it. The reference in Table 3. is indeed a bit confusing lol
