### ISSUE TITLE
can we just use update_location_indices to initiate active_sites_map

### ISSUE THREAD

**Issue by 978326187** [uzh-rpg/rpg_asynet#12]
https://github.com/uzh-rpg/rpg_asynet/blob/e11c0a5c9ef58499e50783b03f755c179e216464/layers/conv_layer_2D.py#L67
https://github.com/uzh-rpg/rpg_asynet/blob/e11c0a5c9ef58499e50783b03f755c179e216464/layers/conv_layer_2D.py#L65

i think the cases in line 65 is included in line 67.

**Comment by MessikommerNico** [comment]
Active site are defined as non-zero sites in the input. Later through the network, active site can become zero without being deactivated. 
The line at 67 catches the cases, in which active sites became zero through the network update (which happens a lot due to ReLU).

**Comment by 978326187** [comment]
does that mean variable **update_location_indices** doesn't include non-zero sites in the input ?

**Comment by MessikommerNico** [comment]
**update_location_indices** includes non-zero sites. But it only considers the sites, which did change from one timestep to the other. Hence, both lines are necessary to get the active site map of the whole activation map

**Comment by 978326187** [comment]
got it ,thanks very much~
