### ISSUE TITLE
some questions about code 

### ISSUE THREAD

**Issue by 978326187** [uzh-rpg/rpg_asynet#13]
https://github.com/uzh-rpg/rpg_asynet/blob/e11c0a5c9ef58499e50783b03f755c179e216464/layers/conv_layer_2D.py#L144
Why do we need padding **active_sites_map**?

**Comment by MessikommerNico** [comment]
This is just done to facilitate the batchwise indexing in Line 151. 
https://github.com/uzh-rpg/rpg_asynet/blob/e11c0a5c9ef58499e50783b03f755c179e216464/layers/conv_layer_2D.py#L151
