### ISSUE TITLE
can i specifies the connections of neurons

### ISSUE THREAD

**Issue by 978326187** [uzh-rpg/rpg_asynet#15]
can i specify the **rule_book_input** and **rule_book_output** as i want.
for example, change the connection just like the picture below.
![image](https://user-images.githubusercontent.com/29019279/98309827-7208bd00-2006-11eb-87a6-6b6cb8fe1ee6.png)

**Comment by MessikommerNico** [comment]
Yes, that should be possible. If you want to propagate the change of the added site further down the network, you also need to update the active_sites_map.

**Comment by 978326187** [comment]
![image](https://user-images.githubusercontent.com/29019279/98350338-2847c300-2056-11eb-8b52-c57da48c4586.png)
i think i should make some change **input_locations** and **output_locations**. am i right?
actually,  i am confused with the code from line 151-181.

**Comment by 978326187** [comment]
i find that the **input_locations** and **output_locations** are one-to-one, shouldn't it be related with filter_size?

**Comment by MessikommerNico** [comment]
A rule in the rule book specifies the connection between neurons i.e. input and output location. Thus, it is always one-to-one. An input site is usually connected to multiple output site, therefore mutliple rules can contain the same input site.
The python code is implemented to achieve as much as possible in matrix from. Maybe it is easier to read the cpp code:
https://github.com/uzh-rpg/rpg_asynet/blob/master/async_sparse_py/src/conv2d.cpp

**Comment by 978326187** [comment]
i think if i wanna adding rules i should change **active_sites_to_update**, but how can i know whether the rules is rightful?
for example, if i use `active_sites_to_update.append([3, 3])`  it doesn't report any error, but if i use `active_sites_to_update.append([0, 3])`, it shows a traceback: 
Traceback (most recent call last):
  File "test.py", line 91, in <module>
    asyn_output = asyn_model.forward(x_asyn)
  File "/storage/xhc/rpg_asynet-master/models/asyn_sparse_vgg.py", line 49, in forward
    rule_book_output=None)
  File "/storage/xhc/rpg_asynet-master/layers/conv_layer_2D.py", line 123, in forward
    output_feature_map.index_add_(dim=0, index=flattend_indices, source=update_term)
IndexError: index out of range in self

**Comment by MessikommerNico** [comment]
**active_sites_to_update** just relates to the current **update_location**. It is not the right place the add new rules
I am not quite sure what your goal is. What do you do if the new rule connects to an inactive output site?
In general, you can append new rules directly to the rulebook in https://github.com/uzh-rpg/rpg_asynet/blob/master/layers/conv_layer_2D.py#L178
But you need to be sure how to update the active site map.

**Comment by 978326187** [comment]
I want to see if adding rules can improves performance of asynet. i also want to use a **if** block to handle the inactive case.
i find that the size of **rule_book_output** and **rule_book_input** is equal, does it mean i should update these two variables at the same time?

**Comment by MessikommerNico** [comment]
Yes, the rule book defines for each kernel index the input and output sites. So there is a one to one mapping between rule_book_input to rule_book_output.

**Comment by 978326187** [comment]
can i just append **output_locations[i_active_site]+1** to achieve my goal?
or i should consider about **position_kernels** and **output_locations**

**Comment by MessikommerNico** [comment]
You should consider all of the three and additionally also the active sites map.
Moreover, if you want to extend the rules based on your image, you also need to increase the kernel size.

**Comment by 978326187** [comment]
ok, thanks for your reply~

**Comment by 978326187** [comment]
what does the variable **active_sites_to_update** conclude? 
i find that this variable is related to **rule_book_output** and **rule_book_inout**, more specifically, **active_sites_to_update[:, 0]**  is related to **rule_book_inout** and **active_sites_to_update[:, 1]** is related to **rule_book_output**.

**Comment by MessikommerNico** [comment]
The variable **active_sites_to_update** includes the relative kernel indices of the active sides in the receptive field of the sites stored in **update_location**, which have at least one active site in the receptive field.  So it is coupled to **update_location** variable, which is given as input to the function.
As I said before, **active_sites_to_update** is not the right place to append new rules. Add the rules directly to the rulebook in https://github.com/uzh-rpg/rpg_asynet/blob/master/layers/conv_layer_2D.py#L178
