### ISSUE TITLE
why should we subtract the filter_size//2?

### ISSUE THREAD

**Issue by 978326187** [uzh-rpg/rpg_asynet#16]
https://github.com/uzh-rpg/rpg_asynet/blob/e11c0a5c9ef58499e50783b03f755c179e216464/layers/conv_layer_2D.py#L149

```
kernel_update_location = shifted_update_location[:, None, :] + self.kernel_indices[None, :, :] \
                                    - self.filter_size // 2
```

**Comment by MessikommerNico** [comment]
This is done as self.kernel_indices contains only positive values. For example for kernel_size=3, we have [0, 1, 2] as self.kernel_indices. As the update location are in the middle of the receptive field, it is necessary to shift the values to [-1, 0, 1]

**Comment by 978326187** [comment]
is that mean the **kernel_update_location ** denotes the next layer 's position?
if the receptive field is 3, update location is **x** , the location in next layer is x-1, x, x+1

**Comment by MessikommerNico** [comment]
Yes, it is used to index the active_sites_map to check which output site is active. If it is inactive, no rule will be constructed.
