### ISSUE TITLE
how can we make asynet trainable?

### ISSUE THREAD

**Issue by 978326187** [uzh-rpg/rpg_asynet#18]
what should  i do if i want training asynet?
i write a training code according to **sparse_VGG_test.py** but the following error reported.
```
Traceback (most recent call last):
  File "train.py", line 45, in <module>
    main()
  File "train.py", line 28, in main
    trainer = AsynSparseVGGModel(settings)
  File "/storage/rpg_asynet-master/training/trainer.py", line 53, in __init__
    self.optimizer = optim.Adam(filter(lambda p: p.requires_grad, self.model.parameters()),
AttributeError: 'asynSparseVGG' object has no attribute 'parameters'
```
**AsynSparseVGGModel** is a VGG model built by **asyn_sparse_vgg.py**

**Comment by MessikommerNico** [comment]
One big of advantage of our approach is the combination of batch_wise learning during training and event-by-event processing during inference. Thus, asynet is not meant to be trained in an asynchronous way. This would require substantial extensions.
Maybe you could elaborate a bit more what your intentions are?

**Comment by 978326187** [comment]
i want to change the rule of the rulebook's building, but the accuracy rate drops dramatically. i guess that's because the parameter trained using SSC is not suitable for the asynet after changing. So i want to make asynet trainable.

**Comment by MessikommerNico** [comment]
Yes, as you said, the performance drop is expected.
If you want to change the training of the sparse convolution, than I would propose that you implement your changes to the Sparse Convolution training (https://github.com/facebookresearch/SparseConvNet.) as we use batch-wise Sparse Convolution for training.
