### ISSUE TITLE
Some question about code on reading N-Cars dataset

### ISSUE THREAD

**Issue by 978326187** [uzh-rpg/rpg_asynet#20]
hi , I download the N-Cars dataset from **http://www.prophesee.ai/dataset-n-cars/**. but after unzip the file, I found that the data format is **.dat**, however, the class NCars read the **.txt** format, is there any method to using NCar dataset.

**Comment by 978326187** [comment]
could you please give a N Car datasets download link with txt format?

**Comment by MessikommerNico** [comment]
Hi
That is unfortunate. We forgot, that we used a parsed version of N-Cars. If you have not already parsed the dataset yourself, I can send you a link to the dataset via mail?

**Comment by 978326187** [comment]
that's really nice ! could you send the link to my email address: 978326187@qq.com?

**Comment by MessikommerNico** [comment]
Sure! I have send you an email.

**Comment by nono-aroca** [comment]
Hi, could you send me the parsed dataset please?

**Comment by 978326187** [comment]
https://drive.google.com/file/d/1vlByGVjqmyYvbzLSIzZzNLfcjfTJijyz/view?usp=sharing

**Comment by lyj1587** [comment]
could you send the link to my email address: 837289390@qq.com?
