### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by zhanghong12345** [uzh-rpg/rpg_asynet#23]
When I was debugging your code, I found an error: 'all' is not a member of 'Eigen'. "all" seems to be a nonexistent attribute, could you please tell me how to solve this problem? I'm looking forward to your reply, my email address: zhanghong@stu.cdu.edu.cn

**Comment by danielgehrig18** [comment]
Hi zhanghong12345,

For this functionality, you need to perform the following instructions:
```
cd async_sparse_py/include
hg clone https://bitbucket.org/eigen/eigen
conda install -c conda-forge pybind11
```
This should download the latest Eigen which has these functions
