### ISSUE TITLE
Error while running Object Detection

### ISSUE THREAD

**Issue by JavierMartinAme** [uzh-rpg/rpg_asynet#24]
Hi, when I run the Object Detection model I get an erroe that I´m not able to solve.
I am working in a conda enviroment that for the task of Classification works well and it is created following this steps:

- conda install -c anaconda pytorch=1.4
- conda install -c anaconda pillow
- bash develop.sh (in the folder of SparseConv Net)
- pip install - r requirements.txt (in the folder of rpg_asynet)
- pip install event_representation_tool/
- conda install -c conda-forge pybind11
- conda install -c anaconda cmake
- pip install async_sparse_py

When my enviroment is already created and a use <conda list> I obtain this:

# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_pytorch_select           0.2                       gpu_0    anaconda
absl-py                   0.9.0                    pypi_0    pypi
async-sparse              0.0.1                    pypi_0    pypi
backcall                  0.1.0                    pypi_0    pypi
blas                      1.0                         mkl    anaconda
bzip2                     1.0.8                h7b6447c_0    anaconda
ca-certificates           2020.10.14                    0    anaconda
cachetools                4.0.0                    pypi_0    pypi
certifi                   2019.11.28               pypi_0    pypi
cffi                      1.14.3           py37he30daa8_0    anaconda
chardet                   3.0.4                    pypi_0    pypi
cmake                     3.18.2               ha30ef3c_0    anaconda
cudatoolkit               10.1.243             h6bb024c_0    anaconda
cudnn                     7.6.5                cuda10.1_0    anaconda
cycler                    0.10.0                   pypi_0    pypi
data                      0.4                      pypi_0    pypi
decorator                 4.4.1                    pypi_0    pypi
event-representations     0.0.1                    pypi_0    pypi
expat                     2.2.10               he6710b0_2    anaconda
freetype                  2.10.4               h5ab3b9f_0    anaconda
funcsigs                  1.0.2                    pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
google-auth               1.11.0                   pypi_0    pypi
google-auth-oauthlib      0.4.1                    pypi_0    pypi
grpcio                    1.26.0                   pypi_0    pypi
idna                      2.8                      pypi_0    pypi
intel-openmp              2020.2                      254    anaconda
ipython                   7.13.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
jedi                      0.16.0                   pypi_0    pypi
jpeg                      9b                   habf39ab_1    anaconda
kiwisolver                1.1.0                    pypi_0    pypi
krb5                      1.18.2               h173b8e3_0    anaconda
lcms2                     2.11                 h396b838_0    anaconda
ld_impl_linux-64          2.33.1               h53a641e_7  
libcurl                   7.71.1               h20c2e04_1    anaconda
libedit                   3.1.20191231         h14c3975_1    anaconda
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0    anaconda
libssh2                   1.9.0                h1ba5d50_1    anaconda
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.2.0                h85742a9_0  
libuv                     1.40.0               h7b6447c_0    anaconda
libwebp-base              1.1.0                h7b6447c_3    anaconda
line-profiler             3.0.2                    pypi_0    pypi
lz4-c                     1.9.2                heb0550a_3    anaconda
markdown                  3.2                      pypi_0    pypi
matplotlib                3.1.3                    pypi_0    pypi
mkl                       2019.4                      243    anaconda
mkl-service               2.3.0            py37he904b0f_0    anaconda
mkl_fft                   1.2.0            py37h23d657b_0    anaconda
mkl_random                1.1.0            py37hd6b4f25_0    anaconda
ncurses                   6.2                  he6710b0_1  
ninja                     1.10.1           py37hfd86e86_0    anaconda
numpy                     1.18.1                   pypi_0    pypi
oauthlib                  3.1.0                    pypi_0    pypi
olefile                   0.46                     py37_0    anaconda
opencv-python             4.2.0.32                 pypi_0    pypi
openssl                   1.1.1j               h27cfd23_0  
parso                     0.6.2                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    7.1.0                    pypi_0    pypi
pip                       21.0.1           py37h06a4308_0  
prompt-toolkit            3.0.3                    pypi_0    pypi
protobuf                  3.11.3                   pypi_0    pypi
ptyprocess                0.6.0                    pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pybind11                  2.4.3                    pypi_0    pypi
pybind11-global           2.6.1                    pypi_0    pypi
pycparser                 2.20                       py_2    anaconda
pygments                  2.5.2                    pypi_0    pypi
pyparsing                 2.4.6                    pypi_0    pypi
python                    3.7.10               hdb3f193_0  
python-dateutil           2.8.1                    pypi_0    pypi
python_abi                3.7                     1_cp37m    conda-forge
pytorch                   1.4.0           cuda101py37h02f0884_0    anaconda
pytz                      2019.3                   pypi_0    pypi
pyyaml                    5.3                      pypi_0    pypi
readline                  8.1                  h27cfd23_0  
requests                  2.22.0                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
rhash                     1.4.0                h1ba5d50_0    anaconda
rsa                       4.0                      pypi_0    pypi
setuptools                52.0.0           py37h06a4308_0  
shutilwhich               1.1.0                    pypi_0    pypi
six                       1.14.0                   pypi_0    pypi
snakeviz                  2.0.1                    pypi_0    pypi
sparseconvnet             0.2                       dev_0    <develop>
sqlite                    3.35.2               hdfb4753_0  
tempdir                   0.7.1                    pypi_0    pypi
tensorboard               2.1.0                    pypi_0    pypi
tk                        8.6.10               hbc83047_0  
torchvision               0.5.0                    pypi_0    pypi
tornado                   6.0.3                    pypi_0    pypi
tqdm                      4.42.1                   pypi_0    pypi
traitlets                 4.3.3                    pypi_0    pypi
urllib3                   1.25.8                   pypi_0    pypi
wcwidth                   0.1.8                    pypi_0    pypi
werkzeug                  1.0.0                    pypi_0    pypi
wheel                     0.36.2             pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.5                h9ceee32_0    anaconda

Finally, when I run the train.py with the NCaltech101_ObjectDetection dataset and the fb_sparse_object_det model, I obtain the following error:

    op = torch._C._jit_get_operation(qualified_op_name)
RuntimeError: No such operator torchvision::nms

**Comment by MessikommerNico** [comment]
Hi,
It seems that this is a problem with the torchvision version. But your environment looks correct.
There is a issue on the pytorch repo regarding this error message: https://github.com/pytorch/vision/issues/1405
Maybe you can find there a solution.
Else, I would try to install pytorch via pip. It should work if you follow the instructions in our readme.

**Comment by JavierMartinAme** [comment]
I have tried it following your instructions in the readme, but when I execute `bash develop.sh` to install the SparseConv Net, I get the following error:

bash develop.sh
running develop
running egg_info
creating sparseconvnet.egg-info
writing sparseconvnet.egg-info/PKG-INFO
writing dependency_links to sparseconvnet.egg-info/dependency_links.txt
writing top-level names to sparseconvnet.egg-info/top_level.txt
writing manifest file 'sparseconvnet.egg-info/SOURCES.txt'
package init file 'sparseconvnet/SCN/__init__.py' not found (or not a regular file)
reading manifest file 'sparseconvnet.egg-info/SOURCES.txt'
writing manifest file 'sparseconvnet.egg-info/SOURCES.txt'
running build_ext
building 'sparseconvnet.SCN' extension
creating build
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/sparseconvnet
creating build/temp.linux-x86_64-3.7/sparseconvnet/SCN
/usr/local/cuda-10.1/bin/nvcc -I/media/DiscoLocal/MUDLAVSP/TFM_javi/SparseConvNet/sparseconvnet/SCN/ -I/home/alumnos/e339870/.conda/envs/prueba/lib/python3.7/site-packages/torch/include -I/home/alumnos/e339870/.conda/envs/prueba/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/alumnos/e339870/.conda/envs/prueba/lib/python3.7/site-packages/torch/include/TH -I/home/alumnos/e339870/.conda/envs/prueba/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-10.1/include -I/home/alumnos/e339870/.conda/envs/prueba/include/python3.7m -c sparseconvnet/SCN/cuda.cu -o build/temp.linux-x86_64-3.7/sparseconvnet/SCN/cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -std=c++14 -Xcompiler -fopenmp -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=SCN -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75
/home/alumnos/e339870/.conda/envs/prueba/lib/python3.7/site-packages/torch/include/c10/util/ArrayRef.h(278): warning: attribute does not apply to any entity

/home/alumnos/e339870/.conda/envs/prueba/lib/python3.7/site-packages/torch/include/c10/core/TensorTypeSet.h(44): warning: integer conversion resulted in a change of sign

/home/alumnos/e339870/.conda/envs/prueba/lib/python3.7/site-packages/torch/include/c10/util/ArrayRef.h(278): warning: attribute does not apply to any entity

/home/alumnos/e339870/.conda/envs/prueba/lib/python3.7/site-packages/torch/include/c10/core/TensorTypeSet.h(44): warning: integer conversion resulted in a change of sign

/usr/include/c++/7/bits/basic_string.tcc: In instantiation of ‘static std::basic_string<_CharT, _Traits, _Alloc>::_Rep* std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_S_create(std::basic_string<_CharT, _Traits, _Alloc>::size_type, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’:
/usr/include/c++/7/bits/basic_string.tcc:578:28:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIterator, const _Alloc&, std::forward_iterator_tag) [with _FwdIterator = const char16_t*; _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>]’
/usr/include/c++/7/bits/basic_string.h:5042:20:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct_aux(_InIterator, _InIterator, const _Alloc&, std::__false_type) [with _InIterator = const char16_t*; _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>]’
/usr/include/c++/7/bits/basic_string.h:5063:24:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIterator, const _Alloc&) [with _InIterator = const char16_t*; _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>]’
/usr/include/c++/7/bits/basic_string.tcc:656:134:   required from ‘std::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _CharT*, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’
/usr/include/c++/7/bits/basic_string.h:6688:95:   required from here
/usr/include/c++/7/bits/basic_string.tcc:1067:16: error: cannot call member function ‘void std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_M_set_sharable() [with _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>]’ without object
       __p->_M_set_sharable();
       ~~~~~~~~~^~
/usr/include/c++/7/bits/basic_string.tcc: In instantiation of ‘static std::basic_string<_CharT, _Traits, _Alloc>::_Rep* std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_S_create(std::basic_string<_CharT, _Traits, _Alloc>::size_type, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’:
/usr/include/c++/7/bits/basic_string.tcc:578:28:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIterator, const _Alloc&, std::forward_iterator_tag) [with _FwdIterator = const char32_t*; _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’
/usr/include/c++/7/bits/basic_string.h:5042:20:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct_aux(_InIterator, _InIterator, const _Alloc&, std::__false_type) [with _InIterator = const char32_t*; _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’
/usr/include/c++/7/bits/basic_string.h:5063:24:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIterator, const _Alloc&) [with _InIterator = const char32_t*; _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’
/usr/include/c++/7/bits/basic_string.tcc:656:134:   required from ‘std::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _CharT*, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’
/usr/include/c++/7/bits/basic_string.h:6693:95:   required from here
/usr/include/c++/7/bits/basic_string.tcc:1067:16: error: cannot call member function ‘void std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_M_set_sharable() [with _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’ without object
error: command '/usr/local/cuda-10.1/bin/nvcc' failed with exit status 1

**Comment by MessikommerNico** [comment]
Have tried the solutions posted on the SparseConv repo regarding this error message? https://github.com/facebookresearch/SparseConvNet/issues/162
You have mentioned before that the sparse classification learning is working for you. How did you install the SparseConv previously?

**Comment by JavierMartinAme** [comment]
In the previous case i just install python 3.7 and then 
```
- conda install -c anaconda pytorch=1.4
- conda install -c anaconda pillow
```
and then when I run `bash develop.sh` it works
