### ISSUE TITLE
Error compiling async_sparse_py

### ISSUE THREAD

**Issue by davidMc0109** [uzh-rpg/rpg_asynet#26]
Sorry for boardering. And I got some problem while compiling the async_sparse_py module while installing.

While compiling async_sparse_py using 
`pip install async_sparse_py`
it fails while processing conv2d.cpp.

The output log is as follows:
`
/home/manchanghai/dvs/rpg_asynet/async_sparse_py/src/conv2d.cpp:216:70: error: converting to ‘AsynSparseConvolution2D::ReturnType {aka std::tuple<Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<float, -1, -1, 0, -1, -1>, Eigen::Matrix<AsynSparseConvolution2D::Site, -1, 1, 0, -1, 1> >}’ from initializer list would use explicit constructor ‘constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {Eigen::Matrix<int, -1, -1, 0, -1, -1>&, Eigen::Matrix<float, -1, -1, 0, -1, -1>&, Eigen::Ref<Eigen::Matrix<AsynSparseConvolution2D::Site, -1, 1, 0, -1, 1>, 0, Eigen::InnerStride<1> >&}; <template-parameter-2-2> = void; _Elements = {Eigen::Matrix<int, -1, -1, 0, -1, -1>, Eigen::Matrix<float, -1, -1, 0, -1, -1>, Eigen::Matrix<AsynSparseConvolution2D::Site, -1, 1, 0, -1, 1>}]’
     return {new_update_location, output_feature_map, active_sites_map};
`

The pybind11 is installed, and the eigen's git repo is cloned at include/eigen. The eigen version used is 3.3.9.
The version of gcc is 5.4.0, and the system used is ubuntu 16.04.

It seems to be caused by the type casting to constexpr or something, but I'm not very sure about that because I'm not familar with C at all(sorry for that). 

Please help to check why this error, and I will try to compiling using different system platform. 

Thank you in advance.
Best regards.

**Comment by MessikommerNico** [comment]
Hi,
Can you please check if you use the correct Eigen version by checking the commit hash: 22edb468236d19ed3f3d700ff37da342035e26d0
We installed again our code by following the instructions in the readme and did not receive any error.

**Comment by MessikommerNico** [comment]
We have now added a specific tag for the Eigen version to the installation instructions in the readme.
You can try if this Eigen version resolves the problem.

**Comment by davidMc0109** [comment]
Solved by upgrading gcc version, however the eigen version seems not matters.
Thanks so much.
