### ISSUE TITLE
Help of running time

### ISSUE THREAD

**Issue by eugenelyj** [uzh-rpg/rpg_asynet#28]
Hi!

I am testing running time of async convolution.

My testing method is to use `time.time()` in python to measure elapsed time of `asyn_model.forward` in unittests/sparse_VGG_test.py.

It shows that `asyn_model` takes about 200ms~300ms to process a single event on i7-9700K, while `fb_model` takes only about 200ms to process 1k events. It is strange, since async should be faster... maybe you know why?

**Comment by MessikommerNico** [comment]
Hi

Yes, it could be that 200ms-300ms is correct, even though it seems high. We reached a runtime of around 80ms for processing one event (see Paper Sec. 4.1). But it also depends on the number of active locations you have in your input representation.
With our work, we show that we can greatly reduce the number of computations needed to process sparse event data. However, this still needs to be translated to better runtime through spezialiced code and hardware.
