### ISSUE TITLE
failed to install eigen

### ISSUE THREAD

**Issue by 978326187** [uzh-rpg/rpg_asynet#5]
https://bitbucket.org/eigen/eigen is 404 now

**Comment by MessikommerNico** [comment]
That is unfortunate. Maybe it is possible to install eigen via conda and adjust the includes in the headers.

**Comment by linharrrrrt** [comment]
download eigen from this link https://gitlab.com/libeigen/eigen/-/tree/master/ , it works. or i uploaded it to baiduyundisk, download it from this share link:
链接: https://pan.baidu.com/s/1nwann-Y67B-z3FKPKyj09w  密码: ljab

**Comment by MessikommerNico** [comment]
Cool, thanks!
