### ISSUE TITLE
Infinite Loop in training

### ISSUE THREAD

**Issue by 978326187** [uzh-rpg/rpg_asynet#6]
https://github.com/uzh-rpg/rpg_asynet/blob/e11c0a5c9ef58499e50783b03f755c179e216464/training/trainer.py#L230
I doubt this **while** module will stop working.

**Comment by MessikommerNico** [comment]
That is correct. We are training to infinity and beyond ;)
That is a bad design choice, thanks for pointing it out. If there will be an update from our side, we will include a parameter for the number of training epochs.
