### ISSUE TITLE
can asynet be trained？

### ISSUE THREAD

**Issue by 978326187** [uzh-rpg/rpg_asynet#7]
i notice that the choice of **model**parameter in seeing.yaml donn't include asynet

![image](https://user-images.githubusercontent.com/29019279/95842216-da061380-0d78-11eb-8f1e-6a6e6977e3c1.png)

is it means we could only train network using SSC and test using asynet？

**Comment by MessikommerNico** [comment]
Hi,
That is correct. The standard batch-wise training of SSC can be used to obtain a trained asynet as the weights/architecture/output of SSC and asynet are identical. However, asynet enables event-by-event processing by propagating a network state through time. This eliminates the need to process redundant information and thus reduces computational complexity.
